#!/bin/bash

#===============================================================================
# BlueTeam-Windsurf - Threat Detection Script
# Detección automática de amenazas en el sistema
#===============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Variables
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
ALERTS_DIR="$BASE_DIR/alerts"
IOCS_DIR="$BASE_DIR/iocs"
RULES_DIR="$BASE_DIR/rules"
LOG_FILE="$BASE_DIR/logs/detect_$(date +%Y%m%d_%H%M%S).log"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Banner
show_banner() {
    echo -e "${CYAN}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║     🔍 BlueTeam Threat Detection System                      ║"
    echo "║        Powered by Windsurf AI                                ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# Logging functions
log() { echo -e "${GREEN}[+]${NC} $1" | tee -a "$LOG_FILE"; }
warn() { echo -e "${YELLOW}[!]${NC} $1" | tee -a "$LOG_FILE"; }
error() { echo -e "${RED}[✗]${NC} $1" | tee -a "$LOG_FILE"; }
alert() { echo -e "${RED}[🚨]${NC} $1" | tee -a "$LOG_FILE"; }
info() { echo -e "${BLUE}[i]${NC} $1" | tee -a "$LOG_FILE"; }

# Create alert file
create_alert() {
    local severity=$1
    local title=$2
    local description=$3
    local iocs=$4
    local mitre=$5
    
    local alert_file="$ALERTS_DIR/$severity/alert_$(date +%Y%m%d_%H%M%S)_$RANDOM.md"
    mkdir -p "$ALERTS_DIR/$severity"
    
    cat > "$alert_file" << EOF
# 🚨 Security Alert - ${severity^^}

**Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Host:** $(hostname)
**User:** $(whoami)

## Description
$title

$description

## Indicators of Compromise (IOCs)
$iocs

## MITRE ATT&CK Mapping
$mitre

## Recommended Actions
- Investigate the affected system
- Check for lateral movement
- Review related logs
- Consider containment if necessary

---
*Generated by BlueTeam-Windsurf Detection System*
EOF
    
    echo "$alert_file"
}

#===============================================================================
# DETECTION FUNCTIONS
#===============================================================================

# Check for suspicious processes
detect_suspicious_processes() {
    log "Checking for suspicious processes..."
    
    local suspicious_procs=(
        "nc -l"
        "ncat -l"
        "netcat"
        "bash -i"
        "python -c"
        "python3 -c"
        "perl -e"
        "ruby -e"
        "php -r"
        "socat"
        "cryptominer"
        "xmrig"
        "minerd"
        "cgminer"
        "bfgminer"
        "cpuminer"
        "stratum"
    )
    
    local found=0
    for proc in "${suspicious_procs[@]}"; do
        if pgrep -f "$proc" > /dev/null 2>&1; then
            alert "SUSPICIOUS PROCESS DETECTED: $proc"
            ps aux | grep -E "$proc" | grep -v grep >> "$LOG_FILE"
            found=1
        fi
    done
    
    # Check for processes with suspicious parent
    local orphan_shells=$(ps -eo pid,ppid,cmd | awk '$2 == 1 && /bash|sh|python|perl|ruby/ {print}')
    if [ -n "$orphan_shells" ]; then
        alert "ORPHAN SHELL PROCESSES DETECTED:"
        echo "$orphan_shells" | tee -a "$LOG_FILE"
        found=1
    fi
    
    if [ $found -eq 0 ]; then
        log "No suspicious processes found"
    else
        create_alert "high" "Suspicious Processes Detected" \
            "Found potentially malicious processes running on the system" \
            "Process patterns: ${suspicious_procs[*]}" \
            "T1059 - Command and Scripting Interpreter"
    fi
}

# Check for suspicious network connections
detect_suspicious_connections() {
    log "Checking for suspicious network connections..."
    
    local found=0
    
    # Check for connections to known bad ports
    local bad_ports="4444|5555|6666|1337|31337|12345|54321"
    local suspicious_conns=$(ss -tunapl 2>/dev/null | grep -E "ESTABLISHED|LISTEN" | grep -E ":($bad_ports)")
    
    if [ -n "$suspicious_conns" ]; then
        alert "SUSPICIOUS PORT CONNECTIONS DETECTED:"
        echo "$suspicious_conns" | tee -a "$LOG_FILE"
        found=1
    fi
    
    # Check for reverse shell patterns
    local reverse_shells=$(ss -tunapl 2>/dev/null | grep -E "bash|nc|ncat|python|perl|ruby|php" | grep ESTABLISHED)
    if [ -n "$reverse_shells" ]; then
        alert "POTENTIAL REVERSE SHELL DETECTED:"
        echo "$reverse_shells" | tee -a "$LOG_FILE"
        found=1
    fi
    
    # Check against IOC IP list
    if [ -f "$IOCS_DIR/ips/ipsum.txt" ]; then
        local current_ips=$(ss -tunapl 2>/dev/null | grep ESTABLISHED | awk '{print $5}' | cut -d: -f1 | sort -u)
        for ip in $current_ips; do
            if grep -q "^$ip" "$IOCS_DIR/ips/ipsum.txt" 2>/dev/null; then
                alert "CONNECTION TO KNOWN MALICIOUS IP: $ip"
                found=1
            fi
        done
    fi
    
    # Check for DNS tunneling (high DNS traffic)
    local dns_conns=$(ss -tunapl 2>/dev/null | grep ":53" | wc -l)
    if [ "$dns_conns" -gt 50 ]; then
        warn "HIGH DNS ACTIVITY DETECTED: $dns_conns connections (possible DNS tunneling)"
        found=1
    fi
    
    if [ $found -eq 0 ]; then
        log "No suspicious network connections found"
    else
        create_alert "high" "Suspicious Network Activity" \
            "Detected potentially malicious network connections" \
            "Check ss -tunapl output for details" \
            "T1071 - Application Layer Protocol, T1572 - Protocol Tunneling"
    fi
}

# Check for persistence mechanisms
detect_persistence() {
    log "Checking for persistence mechanisms..."
    
    local found=0
    
    # Check crontabs
    log "Checking crontabs..."
    for user_cron in /var/spool/cron/crontabs/*; do
        if [ -f "$user_cron" ]; then
            local suspicious_cron=$(grep -E "(curl|wget|bash|nc|python|perl|php|ruby)" "$user_cron" 2>/dev/null)
            if [ -n "$suspicious_cron" ]; then
                alert "SUSPICIOUS CRONTAB ENTRY in $user_cron:"
                echo "$suspicious_cron" | tee -a "$LOG_FILE"
                found=1
            fi
        fi
    done
    
    # Check /etc/crontab
    if [ -f /etc/crontab ]; then
        local etc_cron=$(grep -E "(curl|wget|bash -c|nc |python|perl|php|ruby)" /etc/crontab 2>/dev/null)
        if [ -n "$etc_cron" ]; then
            alert "SUSPICIOUS ENTRY in /etc/crontab:"
            echo "$etc_cron" | tee -a "$LOG_FILE"
            found=1
        fi
    fi
    
    # Check systemd services
    log "Checking systemd services..."
    local suspicious_services=$(systemctl list-unit-files --type=service 2>/dev/null | grep -E "enabled" | awk '{print $1}' | while read svc; do
        local svc_file="/etc/systemd/system/$svc"
        if [ -f "$svc_file" ]; then
            if grep -qE "(curl|wget|nc |bash -c|python|perl)" "$svc_file" 2>/dev/null; then
                echo "$svc"
            fi
        fi
    done)
    
    if [ -n "$suspicious_services" ]; then
        alert "SUSPICIOUS SYSTEMD SERVICES:"
        echo "$suspicious_services" | tee -a "$LOG_FILE"
        found=1
    fi
    
    # Check for unauthorized SSH keys
    log "Checking SSH authorized_keys..."
    for auth_keys in /home/*/.ssh/authorized_keys /root/.ssh/authorized_keys; do
        if [ -f "$auth_keys" ]; then
            local recent_keys=$(find "$auth_keys" -mtime -7 2>/dev/null)
            if [ -n "$recent_keys" ]; then
                warn "RECENTLY MODIFIED SSH KEYS: $auth_keys"
                found=1
            fi
        fi
    done
    
    # Check for SUID binaries
    log "Checking for unusual SUID binaries..."
    local known_suid="/usr/bin/sudo /usr/bin/passwd /usr/bin/chsh /usr/bin/chfn /usr/bin/newgrp /usr/bin/gpasswd /usr/bin/su /usr/bin/mount /usr/bin/umount /usr/bin/pkexec"
    local all_suid=$(find /usr -perm -4000 -type f 2>/dev/null)
    
    for suid in $all_suid; do
        if ! echo "$known_suid" | grep -q "$suid"; then
            warn "UNUSUAL SUID BINARY: $suid"
            found=1
        fi
    done
    
    # Check /etc/passwd for UID 0 users
    local uid0_users=$(awk -F: '($3 == 0) {print $1}' /etc/passwd | grep -v "^root$")
    if [ -n "$uid0_users" ]; then
        alert "NON-ROOT USERS WITH UID 0:"
        echo "$uid0_users" | tee -a "$LOG_FILE"
        found=1
    fi
    
    # Check for hidden files in /tmp and /dev/shm
    local hidden_tmp=$(find /tmp /dev/shm -name ".*" -type f 2>/dev/null | head -20)
    if [ -n "$hidden_tmp" ]; then
        warn "HIDDEN FILES IN /tmp or /dev/shm:"
        echo "$hidden_tmp" | tee -a "$LOG_FILE"
        found=1
    fi
    
    if [ $found -eq 0 ]; then
        log "No persistence mechanisms found"
    else
        create_alert "high" "Persistence Mechanisms Detected" \
            "Found potential persistence mechanisms on the system" \
            "Check crontabs, systemd services, SSH keys, SUID binaries" \
            "T1053 - Scheduled Task/Job, T1543 - Create or Modify System Process"
    fi
}

# Check authentication logs
detect_auth_anomalies() {
    log "Checking authentication logs..."
    
    local found=0
    local auth_log="/var/log/auth.log"
    
    if [ ! -f "$auth_log" ]; then
        auth_log="/var/log/secure"
    fi
    
    if [ -f "$auth_log" ]; then
        # Failed SSH logins
        local failed_ssh=$(grep -c "Failed password" "$auth_log" 2>/dev/null || echo 0)
        if [ "$failed_ssh" -gt 10 ]; then
            alert "HIGH NUMBER OF FAILED SSH LOGINS: $failed_ssh"
            grep "Failed password" "$auth_log" | tail -10 >> "$LOG_FILE"
            found=1
        fi
        
        # Successful logins from unusual IPs
        local successful_logins=$(grep "Accepted" "$auth_log" 2>/dev/null | tail -20)
        if [ -n "$successful_logins" ]; then
            info "Recent successful logins:"
            echo "$successful_logins" | tee -a "$LOG_FILE"
        fi
        
        # Sudo failures
        local sudo_failures=$(grep -c "sudo.*authentication failure" "$auth_log" 2>/dev/null || echo 0)
        if [ "$sudo_failures" -gt 5 ]; then
            warn "MULTIPLE SUDO AUTHENTICATION FAILURES: $sudo_failures"
            found=1
        fi
        
        # New user creation
        local new_users=$(grep "useradd\|adduser" "$auth_log" 2>/dev/null | tail -5)
        if [ -n "$new_users" ]; then
            warn "RECENT USER CREATION ACTIVITY:"
            echo "$new_users" | tee -a "$LOG_FILE"
            found=1
        fi
        
        # Privilege escalation attempts
        local priv_esc=$(grep -E "sudo.*COMMAND|su\[" "$auth_log" 2>/dev/null | grep -v "COMMAND=/usr/bin" | tail -10)
        if [ -n "$priv_esc" ]; then
            info "Recent privilege escalation:"
            echo "$priv_esc" | tee -a "$LOG_FILE"
        fi
    else
        warn "Auth log not found"
    fi
    
    if [ $found -eq 0 ]; then
        log "No authentication anomalies found"
    else
        create_alert "medium" "Authentication Anomalies" \
            "Detected unusual authentication activity" \
            "Check $auth_log for details" \
            "T1078 - Valid Accounts, T1110 - Brute Force"
    fi
}

# Check for malware signatures with YARA
detect_malware_yara() {
    log "Scanning for malware with YARA..."
    
    if ! command -v yara &> /dev/null; then
        warn "YARA not installed, skipping malware scan"
        return
    fi
    
    local found=0
    local yara_rules="$RULES_DIR/yara"
    
    if [ -d "$yara_rules" ]; then
        # Scan /tmp
        for rule_file in "$yara_rules"/*.yar "$yara_rules"/*/*.yar; do
            if [ -f "$rule_file" ]; then
                local matches=$(yara -r "$rule_file" /tmp 2>/dev/null | head -20)
                if [ -n "$matches" ]; then
                    alert "YARA MATCHES FOUND:"
                    echo "$matches" | tee -a "$LOG_FILE"
                    found=1
                fi
            fi
        done
    else
        warn "No YARA rules found in $yara_rules"
    fi
    
    if [ $found -eq 0 ]; then
        log "No malware signatures detected"
    else
        create_alert "critical" "Malware Detected" \
            "YARA rules matched potential malware on the system" \
            "Check YARA scan results" \
            "T1204 - User Execution"
    fi
}

# Check system integrity
detect_system_changes() {
    log "Checking system integrity..."
    
    local found=0
    
    # Check for modified system binaries
    local critical_bins="/bin/ls /bin/ps /bin/netstat /usr/bin/ssh /usr/bin/sudo /usr/bin/passwd"
    for bin in $critical_bins; do
        if [ -f "$bin" ]; then
            local mod_time=$(stat -c %Y "$bin" 2>/dev/null)
            local current_time=$(date +%s)
            local diff=$((current_time - mod_time))
            
            # If modified in last 7 days
            if [ "$diff" -lt 604800 ]; then
                warn "RECENTLY MODIFIED SYSTEM BINARY: $bin ($(stat -c %y "$bin"))"
                found=1
            fi
        fi
    done
    
    # Check /etc/passwd and /etc/shadow
    for critical_file in /etc/passwd /etc/shadow /etc/sudoers; do
        if [ -f "$critical_file" ]; then
            local mod_time=$(stat -c %Y "$critical_file" 2>/dev/null)
            local current_time=$(date +%s)
            local diff=$((current_time - mod_time))
            
            if [ "$diff" -lt 86400 ]; then
                warn "RECENTLY MODIFIED CRITICAL FILE: $critical_file"
                found=1
            fi
        fi
    done
    
    # Check for world-writable files in /etc
    local world_writable=$(find /etc -perm -002 -type f 2>/dev/null | head -10)
    if [ -n "$world_writable" ]; then
        warn "WORLD-WRITABLE FILES IN /etc:"
        echo "$world_writable" | tee -a "$LOG_FILE"
        found=1
    fi
    
    if [ $found -eq 0 ]; then
        log "System integrity check passed"
    else
        create_alert "high" "System Integrity Issues" \
            "Detected modifications to critical system files" \
            "Check recently modified binaries and config files" \
            "T1222 - File and Directory Permissions Modification"
    fi
}

# Check for rootkits
detect_rootkits() {
    log "Checking for rootkits..."
    
    local found=0
    
    # Check for hidden processes
    local ps_count=$(ps aux | wc -l)
    local proc_count=$(ls -d /proc/[0-9]* 2>/dev/null | wc -l)
    
    if [ $((proc_count - ps_count)) -gt 5 ]; then
        alert "POSSIBLE HIDDEN PROCESSES DETECTED"
        found=1
    fi
    
    # Check for hidden ports
    local ss_ports=$(ss -tunapl 2>/dev/null | grep LISTEN | wc -l)
    local netstat_ports=$(netstat -tunapl 2>/dev/null | grep LISTEN | wc -l)
    
    if [ $((ss_ports - netstat_ports)) -gt 2 ] 2>/dev/null; then
        warn "DISCREPANCY IN PORT LISTINGS (possible hidden ports)"
        found=1
    fi
    
    # Check for LKM rootkits
    local suspicious_modules=$(lsmod | grep -vE "^(Module|nvidia|snd_|usb|hid|i2c|drm|video|acpi|battery|thermal|processor|button|intel|amd|ata|ahci|sd_|sr_|cdrom|loop|fuse|overlay|nf_|xt_|ip_|ipt_|nft_|br_|bridge|8021q|veth|tun|tap|bonding|team|vlan|macvlan|ipvlan|vxlan|geneve|wireguard|bluetooth|btusb|rfkill|cfg80211|mac80211|iwl|ath|rtl|r8|realtek|e1000|igb|ixgbe|mlx|virtio|vmw|hyperv|xen|kvm)" | awk '{print $1}')
    
    if [ -n "$suspicious_modules" ]; then
        warn "UNUSUAL KERNEL MODULES LOADED:"
        echo "$suspicious_modules" | tee -a "$LOG_FILE"
        found=1
    fi
    
    # Run chkrootkit if available
    if command -v chkrootkit &> /dev/null; then
        local rootkit_check=$(chkrootkit 2>/dev/null | grep -i "infected\|INFECTED")
        if [ -n "$rootkit_check" ]; then
            alert "CHKROOTKIT DETECTED INFECTION:"
            echo "$rootkit_check" | tee -a "$LOG_FILE"
            found=1
        fi
    fi
    
    # Run rkhunter if available
    if command -v rkhunter &> /dev/null; then
        local rk_check=$(rkhunter --check --skip-keypress --report-warnings-only 2>/dev/null | grep -i "warning")
        if [ -n "$rk_check" ]; then
            warn "RKHUNTER WARNINGS:"
            echo "$rk_check" | tee -a "$LOG_FILE"
            found=1
        fi
    fi
    
    if [ $found -eq 0 ]; then
        log "No rootkit indicators found"
    else
        create_alert "critical" "Possible Rootkit Detected" \
            "Found indicators of possible rootkit infection" \
            "Hidden processes, ports, or suspicious kernel modules" \
            "T1014 - Rootkit"
    fi
}

# Analyze specific log file
analyze_log_file() {
    local log_file=$1
    log "Analyzing log file: $log_file"
    
    if [ ! -f "$log_file" ]; then
        error "Log file not found: $log_file"
        return 1
    fi
    
    local found=0
    
    # Common attack patterns
    local patterns=(
        "SQL injection:(\"|'|;|--|/\*|\*/|union|select|insert|update|delete|drop|exec|execute)"
        "XSS:(<script|javascript:|onerror=|onload=|onclick=)"
        "Path traversal:(\.\.\/|\.\.\\\\|%2e%2e)"
        "Command injection:(;|\||&|`|\$\()"
        "Shell access:(\/bin\/bash|\/bin\/sh|cmd\.exe|powershell)"
        "Suspicious user-agent:(nikto|sqlmap|nmap|masscan|dirbuster|gobuster|wfuzz)"
    )
    
    for pattern_def in "${patterns[@]}"; do
        local name="${pattern_def%%:*}"
        local pattern="${pattern_def#*:}"
        
        local matches=$(grep -iE "$pattern" "$log_file" 2>/dev/null | head -10)
        if [ -n "$matches" ]; then
            alert "POTENTIAL $name DETECTED in $log_file:"
            echo "$matches" | tee -a "$LOG_FILE"
            found=1
        fi
    done
    
    # Check for error spikes
    local error_count=$(grep -ciE "(error|fail|denied|unauthorized|forbidden)" "$log_file" 2>/dev/null || echo 0)
    if [ "$error_count" -gt 100 ]; then
        warn "HIGH ERROR COUNT in $log_file: $error_count"
        found=1
    fi
    
    if [ $found -eq 0 ]; then
        log "No suspicious patterns found in $log_file"
    fi
}

# Full system scan
full_scan() {
    log "Starting full system threat detection scan..."
    echo ""
    
    detect_suspicious_processes
    echo ""
    
    detect_suspicious_connections
    echo ""
    
    detect_persistence
    echo ""
    
    detect_auth_anomalies
    echo ""
    
    detect_system_changes
    echo ""
    
    detect_rootkits
    echo ""
    
    detect_malware_yara
    echo ""
    
    # Analyze common log files
    for logfile in /var/log/auth.log /var/log/syslog /var/log/apache2/access.log /var/log/nginx/access.log; do
        if [ -f "$logfile" ]; then
            analyze_log_file "$logfile"
            echo ""
        fi
    done
    
    log "Full scan completed. Results saved to: $LOG_FILE"
}

# Quick scan
quick_scan() {
    log "Starting quick threat detection scan..."
    echo ""
    
    detect_suspicious_processes
    echo ""
    
    detect_suspicious_connections
    echo ""
    
    detect_auth_anomalies
    echo ""
    
    log "Quick scan completed. Results saved to: $LOG_FILE"
}

# Network scan
network_scan() {
    log "Starting network threat detection scan..."
    echo ""
    
    detect_suspicious_connections
    echo ""
    
    # Additional network checks
    log "Active connections:"
    ss -tunapl | grep ESTABLISHED | head -20 | tee -a "$LOG_FILE"
    echo ""
    
    log "Listening ports:"
    ss -tunapl | grep LISTEN | tee -a "$LOG_FILE"
    echo ""
    
    log "Network scan completed. Results saved to: $LOG_FILE"
}

# Usage
usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --full          Full system scan (all checks)"
    echo "  --quick         Quick scan (processes, connections, auth)"
    echo "  --network       Network-focused scan"
    echo "  --processes     Check suspicious processes only"
    echo "  --connections   Check network connections only"
    echo "  --persistence   Check persistence mechanisms only"
    echo "  --auth          Check authentication logs only"
    echo "  --integrity     Check system integrity only"
    echo "  --rootkit       Check for rootkits only"
    echo "  --malware       Scan for malware with YARA"
    echo "  --logs FILE     Analyze specific log file"
    echo "  -h, --help      Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 --full"
    echo "  $0 --quick"
    echo "  $0 --logs /var/log/auth.log"
}

#===============================================================================
# MAIN
#===============================================================================

main() {
    show_banner
    
    mkdir -p "$(dirname "$LOG_FILE")"
    
    case "${1:-}" in
        --full)
            full_scan
            ;;
        --quick)
            quick_scan
            ;;
        --network)
            network_scan
            ;;
        --processes)
            detect_suspicious_processes
            ;;
        --connections)
            detect_suspicious_connections
            ;;
        --persistence)
            detect_persistence
            ;;
        --auth)
            detect_auth_anomalies
            ;;
        --integrity)
            detect_system_changes
            ;;
        --rootkit)
            detect_rootkits
            ;;
        --malware)
            detect_malware_yara
            ;;
        --logs)
            if [ -n "${2:-}" ]; then
                analyze_log_file "$2"
            else
                error "Please specify a log file"
                usage
                exit 1
            fi
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        "")
            full_scan
            ;;
        *)
            error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
}

main "$@"
