#!/bin/bash

#===============================================================================
# BlueTeam-Windsurf - Threat Hunter
# Proactive threat hunting based on MITRE ATT&CK techniques
#===============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Variables
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
HUNT_LOG="$BASE_DIR/logs/threat_hunt_$(date +%Y%m%d_%H%M%S).log"
FINDINGS_DIR="$BASE_DIR/alerts/hunt"

# Banner
show_banner() {
    echo -e "${CYAN}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║     🎯 BlueTeam Threat Hunter                                ║"
    echo "║        MITRE ATT&CK Based Hunting                            ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# Logging
log() { echo -e "${GREEN}[+]${NC} $1" | tee -a "$HUNT_LOG"; }
warn() { echo -e "${YELLOW}[!]${NC} $1" | tee -a "$HUNT_LOG"; }
error() { echo -e "${RED}[✗]${NC} $1" | tee -a "$HUNT_LOG"; }
alert() { echo -e "${RED}[🎯]${NC} $1" | tee -a "$HUNT_LOG"; }
info() { echo -e "${BLUE}[i]${NC} $1" | tee -a "$HUNT_LOG"; }

# Create finding
create_finding() {
    local technique=$1
    local title=$2
    local description=$3
    local evidence=$4
    
    mkdir -p "$FINDINGS_DIR"
    local finding_file="$FINDINGS_DIR/hunt_$(date +%Y%m%d_%H%M%S)_$RANDOM.md"
    
    cat > "$finding_file" << EOF
# 🎯 Threat Hunt Finding

**Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Technique:** $technique
**Title:** $title

## Description
$description

## Evidence
\`\`\`
$evidence
\`\`\`

## Recommendations
- Investigate the finding
- Correlate with other events
- Consider containment if malicious

---
*Generated by BlueTeam Threat Hunter*
EOF
    
    echo "$finding_file"
}

#===============================================================================
# PERSISTENCE HUNTING (TA0003)
#===============================================================================

hunt_persistence() {
    log "🔍 Hunting for Persistence Mechanisms (TA0003)..."
    echo ""
    
    local found=0
    
    # T1053 - Scheduled Tasks/Cron
    info "Checking scheduled tasks (T1053)..."
    
    # User crontabs
    for crontab in /var/spool/cron/crontabs/*; do
        if [ -f "$crontab" ]; then
            local suspicious
            suspicious=$(grep -E "(curl|wget|nc|bash|python|perl|php|ruby|\.sh)" "$crontab" 2>/dev/null || true)
            if [ -n "$suspicious" ]; then
                alert "Suspicious crontab entry found in $crontab"
                echo "$suspicious" | tee -a "$HUNT_LOG"
                create_finding "T1053" "Suspicious Crontab" "Found suspicious entry in $crontab" "$suspicious"
                found=1
            fi
        fi
    done
    
    # System crontabs
    for crondir in /etc/cron.d /etc/cron.daily /etc/cron.hourly /etc/cron.weekly /etc/cron.monthly; do
        if [ -d "$crondir" ]; then
            local suspicious
            suspicious=$(grep -rE "(curl|wget|nc|bash -c|python -c|perl -e)" "$crondir" 2>/dev/null || true)
            if [ -n "$suspicious" ]; then
                alert "Suspicious cron entry in $crondir"
                echo "$suspicious" | tee -a "$HUNT_LOG"
                found=1
            fi
        fi
    done
    
    # T1543 - Systemd Services
    info "Checking systemd services (T1543)..."
    
    # Recently created services
    local recent_services
    recent_services=$(find /etc/systemd/system /usr/lib/systemd/system -name "*.service" -mtime -7 2>/dev/null || true)
    if [ -n "$recent_services" ]; then
        warn "Recently created/modified systemd services:"
        echo "$recent_services" | tee -a "$HUNT_LOG"
        
        for svc in $recent_services; do
            if grep -qE "(curl|wget|nc|bash|python|perl|/tmp/|/dev/shm/)" "$svc" 2>/dev/null; then
                alert "Suspicious service: $svc"
                cat "$svc" >> "$HUNT_LOG"
                found=1
            fi
        done
    fi
    
    # T1547 - Boot/Logon Autostart
    info "Checking autostart locations (T1547)..."
    
    # rc.local
    if [ -f /etc/rc.local ]; then
        local rclocal
        rclocal=$(grep -vE "^#|^$|^exit" /etc/rc.local 2>/dev/null || true)
        if [ -n "$rclocal" ]; then
            warn "Commands in /etc/rc.local:"
            echo "$rclocal" | tee -a "$HUNT_LOG"
        fi
    fi
    
    # init.d scripts
    local recent_init
    recent_init=$(find /etc/init.d -type f -mtime -7 2>/dev/null || true)
    if [ -n "$recent_init" ]; then
        warn "Recently modified init.d scripts:"
        echo "$recent_init" | tee -a "$HUNT_LOG"
    fi
    
    # T1546 - Event Triggered Execution
    info "Checking event triggers (T1546)..."
    
    # .bashrc/.profile modifications
    for profile in /home/*/.bashrc /home/*/.bash_profile /home/*/.profile /root/.bashrc /root/.profile; do
        if [ -f "$profile" ]; then
            local suspicious
            suspicious=$(grep -E "(curl|wget|nc|python|perl|base64|eval)" "$profile" 2>/dev/null || true)
            if [ -n "$suspicious" ]; then
                alert "Suspicious entry in $profile"
                echo "$suspicious" | tee -a "$HUNT_LOG"
                found=1
            fi
        fi
    done
    
    # T1098 - Account Manipulation
    info "Checking for account manipulation (T1098)..."
    
    # Users with UID 0
    local uid0
    uid0=$(awk -F: '($3 == 0) {print $1}' /etc/passwd | grep -v "^root$" || true)
    if [ -n "$uid0" ]; then
        alert "Non-root users with UID 0:"
        echo "$uid0" | tee -a "$HUNT_LOG"
        found=1
    fi
    
    # Users with no password
    local nopass
    nopass=$(awk -F: '($2 == "" || $2 == "!") {print $1}' /etc/shadow 2>/dev/null || true)
    if [ -n "$nopass" ]; then
        warn "Users with no/disabled password:"
        echo "$nopass" | tee -a "$HUNT_LOG"
    fi
    
    # Recently added users
    local recent_users
    recent_users=$(grep -E "useradd|adduser" /var/log/auth.log 2>/dev/null | tail -10 || true)
    if [ -n "$recent_users" ]; then
        info "Recent user additions:"
        echo "$recent_users" | tee -a "$HUNT_LOG"
    fi
    
    # SSH authorized_keys
    info "Checking SSH keys (T1098.004)..."
    for authkeys in /home/*/.ssh/authorized_keys /root/.ssh/authorized_keys; do
        if [ -f "$authkeys" ]; then
            local keycount
            keycount=$(wc -l < "$authkeys")
            if [ "$keycount" -gt 0 ]; then
                info "Found $keycount SSH keys in $authkeys"
                # Check for recently added keys
                if [ "$(find "$authkeys" -mtime -7 2>/dev/null)" ]; then
                    warn "SSH keys file recently modified: $authkeys"
                fi
            fi
        fi
    done
    
    if [ $found -eq 0 ]; then
        log "No persistence mechanisms found"
    fi
    
    echo ""
}

#===============================================================================
# PRIVILEGE ESCALATION HUNTING (TA0004)
#===============================================================================

hunt_privilege_escalation() {
    log "🔍 Hunting for Privilege Escalation (TA0004)..."
    echo ""
    
    local found=0
    
    # T1548 - SUID/SGID Abuse
    info "Checking SUID binaries (T1548)..."
    
    local known_suid="/usr/bin/sudo /usr/bin/su /usr/bin/passwd /usr/bin/chsh /usr/bin/chfn /usr/bin/newgrp /usr/bin/gpasswd /usr/bin/mount /usr/bin/umount /usr/bin/pkexec /usr/bin/crontab /usr/bin/at /usr/bin/ssh-agent /usr/lib/openssh/ssh-keysign /usr/lib/dbus-1.0/dbus-daemon-launch-helper /usr/lib/policykit-1/polkit-agent-helper-1"
    
    while IFS= read -r suid; do
        if ! echo "$known_suid" | grep -q "$suid"; then
            warn "Unusual SUID binary: $suid"
            ls -la "$suid" >> "$HUNT_LOG"
            found=1
        fi
    done < <(find /usr /bin /sbin -perm -4000 -type f 2>/dev/null)
    
    # SGID binaries
    local sgid_bins
    sgid_bins=$(find /usr /bin /sbin -perm -2000 -type f 2>/dev/null | head -20 || true)
    if [ -n "$sgid_bins" ]; then
        info "SGID binaries found:"
        echo "$sgid_bins" | head -10 | tee -a "$HUNT_LOG"
    fi
    
    # T1548.003 - Sudo Abuse
    info "Checking sudo configuration (T1548.003)..."
    
    # NOPASSWD entries
    local nopasswd
    nopasswd=$(grep -r "NOPASSWD" /etc/sudoers /etc/sudoers.d/ 2>/dev/null || true)
    if [ -n "$nopasswd" ]; then
        warn "NOPASSWD sudo entries found:"
        echo "$nopasswd" | tee -a "$HUNT_LOG"
    fi
    
    # Dangerous sudo permissions
    local dangerous_sudo
    dangerous_sudo=$(grep -rE "(ALL.*ALL|NOPASSWD.*ALL|!/)" /etc/sudoers /etc/sudoers.d/ 2>/dev/null || true)
    if [ -n "$dangerous_sudo" ]; then
        warn "Potentially dangerous sudo permissions:"
        echo "$dangerous_sudo" | tee -a "$HUNT_LOG"
    fi
    
    # T1068 - Exploitation for Privilege Escalation
    info "Checking for exploitation indicators (T1068)..."
    
    # Core dumps
    local coredumps
    coredumps=$(find /var/crash /tmp /var/tmp -name "core*" -o -name "*.core" 2>/dev/null | head -10 || true)
    if [ -n "$coredumps" ]; then
        warn "Core dumps found (possible exploitation):"
        echo "$coredumps" | tee -a "$HUNT_LOG"
    fi
    
    # Capabilities
    info "Checking file capabilities..."
    local caps
    caps=$(getcap -r / 2>/dev/null | grep -v "^$" | head -20 || true)
    if [ -n "$caps" ]; then
        info "Files with capabilities:"
        echo "$caps" | tee -a "$HUNT_LOG"
        
        # Check for dangerous capabilities
        if echo "$caps" | grep -qE "(cap_setuid|cap_setgid|cap_sys_admin|cap_sys_ptrace)"; then
            warn "Dangerous capabilities found!"
            found=1
        fi
    fi
    
    # World-writable directories in PATH
    info "Checking PATH for world-writable directories..."
    IFS=':' read -ra PATHDIRS <<< "$PATH"
    for dir in "${PATHDIRS[@]}"; do
        if [ -d "$dir" ] && [ -w "$dir" ] && [ "$(stat -c %a "$dir" 2>/dev/null)" = "777" ]; then
            alert "World-writable directory in PATH: $dir"
            found=1
        fi
    done
    
    if [ $found -eq 0 ]; then
        log "No privilege escalation indicators found"
    fi
    
    echo ""
}

#===============================================================================
# DEFENSE EVASION HUNTING (TA0005)
#===============================================================================

hunt_defense_evasion() {
    log "🔍 Hunting for Defense Evasion (TA0005)..."
    echo ""
    
    local found=0
    
    # T1070 - Indicator Removal
    info "Checking for log tampering (T1070)..."
    
    # Empty or truncated logs
    for logfile in /var/log/auth.log /var/log/syslog /var/log/messages /var/log/secure; do
        if [ -f "$logfile" ]; then
            local size
            size=$(stat -c %s "$logfile" 2>/dev/null || echo 0)
            if [ "$size" -lt 100 ]; then
                alert "Suspiciously small log file: $logfile ($size bytes)"
                found=1
            fi
        fi
    done
    
    # Check for history file tampering
    for histfile in /home/*/.bash_history /root/.bash_history; do
        if [ -f "$histfile" ]; then
            # Check if linked to /dev/null
            if [ -L "$histfile" ]; then
                local target
                target=$(readlink "$histfile")
                if [ "$target" = "/dev/null" ]; then
                    alert "History file linked to /dev/null: $histfile"
                    found=1
                fi
            fi
            # Check if empty but should have content
            if [ ! -s "$histfile" ]; then
                warn "Empty history file: $histfile"
            fi
        fi
    done
    
    # T1027 - Obfuscated Files
    info "Checking for obfuscated files (T1027)..."
    
    # Base64 encoded scripts
    local b64_scripts
    b64_scripts=$(find /tmp /var/tmp /dev/shm -type f -exec grep -l "base64" {} \; 2>/dev/null | head -10 || true)
    if [ -n "$b64_scripts" ]; then
        warn "Files with base64 content:"
        echo "$b64_scripts" | tee -a "$HUNT_LOG"
    fi
    
    # T1564 - Hidden Artifacts
    info "Checking for hidden files (T1564)..."
    
    # Hidden files in suspicious locations
    local hidden
    hidden=$(find /tmp /var/tmp /dev/shm -name ".*" -type f 2>/dev/null | head -20 || true)
    if [ -n "$hidden" ]; then
        warn "Hidden files in temp directories:"
        echo "$hidden" | tee -a "$HUNT_LOG"
        found=1
    fi
    
    # Hidden directories
    local hidden_dirs
    hidden_dirs=$(find / -maxdepth 3 -name ".. " -o -name "..." -o -name ".  " 2>/dev/null || true)
    if [ -n "$hidden_dirs" ]; then
        alert "Suspicious hidden directories:"
        echo "$hidden_dirs" | tee -a "$HUNT_LOG"
        found=1
    fi
    
    # T1014 - Rootkit Detection
    info "Checking for rootkit indicators (T1014)..."
    
    # Compare ps and /proc
    local ps_count
    local proc_count
    ps_count=$(ps aux | wc -l)
    proc_count=$(ls -d /proc/[0-9]* 2>/dev/null | wc -l)
    
    if [ $((proc_count - ps_count)) -gt 10 ]; then
        alert "Process count discrepancy (possible hidden processes)"
        alert "ps shows $ps_count, /proc shows $proc_count"
        found=1
    fi
    
    # Check for suspicious kernel modules
    local suspicious_mods
    suspicious_mods=$(lsmod | awk '{print $1}' | while read -r mod; do
        if ! modinfo "$mod" &>/dev/null; then
            echo "$mod"
        fi
    done || true)
    
    if [ -n "$suspicious_mods" ]; then
        alert "Kernel modules without modinfo:"
        echo "$suspicious_mods" | tee -a "$HUNT_LOG"
        found=1
    fi
    
    # T1562 - Impair Defenses
    info "Checking security tool status (T1562)..."
    
    # Check if security tools are disabled
    for service in auditd fail2ban ufw iptables apparmor selinux; do
        if command -v systemctl &>/dev/null; then
            if systemctl is-enabled "$service" &>/dev/null; then
                if ! systemctl is-active "$service" &>/dev/null; then
                    warn "Security service not running: $service"
                fi
            fi
        fi
    done
    
    # Check iptables rules
    local iptables_rules
    iptables_rules=$(iptables -L -n 2>/dev/null | grep -c "^" || echo 0)
    if [ "$iptables_rules" -lt 5 ]; then
        warn "Very few iptables rules ($iptables_rules) - firewall may be disabled"
    fi
    
    if [ $found -eq 0 ]; then
        log "No defense evasion indicators found"
    fi
    
    echo ""
}

#===============================================================================
# LATERAL MOVEMENT HUNTING (TA0008)
#===============================================================================

hunt_lateral_movement() {
    log "🔍 Hunting for Lateral Movement (TA0008)..."
    echo ""
    
    local found=0
    
    # T1021 - Remote Services
    info "Checking remote service usage (T1021)..."
    
    # SSH connections
    local ssh_conns
    ssh_conns=$(ss -tunapl 2>/dev/null | grep ":22" | grep ESTABLISHED || true)
    if [ -n "$ssh_conns" ]; then
        info "Active SSH connections:"
        echo "$ssh_conns" | tee -a "$HUNT_LOG"
    fi
    
    # Recent SSH logins from unusual IPs
    local ssh_logins
    ssh_logins=$(grep "Accepted" /var/log/auth.log 2>/dev/null | tail -20 || true)
    if [ -n "$ssh_logins" ]; then
        info "Recent SSH logins:"
        echo "$ssh_logins" | tee -a "$HUNT_LOG"
    fi
    
    # T1021.002 - SMB/Windows Admin Shares
    info "Checking SMB connections (T1021.002)..."
    local smb_conns
    smb_conns=$(ss -tunapl 2>/dev/null | grep -E ":(445|139)" || true)
    if [ -n "$smb_conns" ]; then
        warn "SMB connections detected:"
        echo "$smb_conns" | tee -a "$HUNT_LOG"
    fi
    
    # T1021.004 - SSH
    info "Checking for SSH key usage..."
    
    # SSH agent
    if [ -n "$SSH_AUTH_SOCK" ]; then
        local ssh_keys
        ssh_keys=$(ssh-add -l 2>/dev/null || true)
        if [ -n "$ssh_keys" ]; then
            info "SSH keys in agent:"
            echo "$ssh_keys" | tee -a "$HUNT_LOG"
        fi
    fi
    
    # T1570 - Lateral Tool Transfer
    info "Checking for tool transfer indicators (T1570)..."
    
    # Recent file transfers
    local transfers
    transfers=$(grep -E "(scp|rsync|wget|curl)" /var/log/auth.log /var/log/syslog 2>/dev/null | tail -20 || true)
    if [ -n "$transfers" ]; then
        info "Recent file transfer activity:"
        echo "$transfers" | tee -a "$HUNT_LOG"
    fi
    
    # Files in /tmp from other hosts
    local tmp_files
    tmp_files=$(find /tmp /var/tmp -type f -mtime -1 -size +1M 2>/dev/null | head -10 || true)
    if [ -n "$tmp_files" ]; then
        warn "Large recent files in temp directories:"
        echo "$tmp_files" | tee -a "$HUNT_LOG"
        for f in $tmp_files; do
            file "$f" >> "$HUNT_LOG" 2>/dev/null || true
        done
    fi
    
    if [ $found -eq 0 ]; then
        log "No lateral movement indicators found"
    fi
    
    echo ""
}

#===============================================================================
# COMMAND AND CONTROL HUNTING (TA0011)
#===============================================================================

hunt_c2() {
    log "🔍 Hunting for Command & Control (TA0011)..."
    echo ""
    
    local found=0
    
    # T1071 - Application Layer Protocol
    info "Checking for C2 traffic patterns (T1071)..."
    
    # Unusual outbound connections
    local outbound
    outbound=$(ss -tunapl 2>/dev/null | grep ESTABLISHED | grep -v "127.0.0.1" || true)
    if [ -n "$outbound" ]; then
        info "Outbound connections:"
        echo "$outbound" | tee -a "$HUNT_LOG"
    fi
    
    # Connections to unusual ports
    local unusual_ports
    unusual_ports=$(ss -tunapl 2>/dev/null | grep ESTABLISHED | grep -E ":(4444|5555|6666|1337|31337|8080|8443|9001)" || true)
    if [ -n "$unusual_ports" ]; then
        alert "Connections to suspicious ports:"
        echo "$unusual_ports" | tee -a "$HUNT_LOG"
        found=1
    fi
    
    # T1572 - Protocol Tunneling
    info "Checking for tunneling (T1572)..."
    
    # DNS tunneling indicators
    local dns_queries
    dns_queries=$(ss -tunapl 2>/dev/null | grep ":53" | wc -l || echo 0)
    if [ "$dns_queries" -gt 50 ]; then
        warn "High DNS activity ($dns_queries connections) - possible DNS tunneling"
        found=1
    fi
    
    # ICMP tunneling
    if ping -c 1 127.0.0.1 &>/dev/null; then
        local icmp_procs
        icmp_procs=$(ps aux | grep -E "(ptunnel|icmpsh|icmptunnel)" | grep -v grep || true)
        if [ -n "$icmp_procs" ]; then
            alert "ICMP tunneling tools detected:"
            echo "$icmp_procs" | tee -a "$HUNT_LOG"
            found=1
        fi
    fi
    
    # T1573 - Encrypted Channel
    info "Checking for encrypted channels (T1573)..."
    
    # SSL/TLS connections to unusual destinations
    local ssl_conns
    ssl_conns=$(ss -tunapl 2>/dev/null | grep ":443" | grep ESTABLISHED || true)
    if [ -n "$ssl_conns" ]; then
        info "HTTPS connections:"
        echo "$ssl_conns" | head -10 | tee -a "$HUNT_LOG"
    fi
    
    # T1095 - Non-Application Layer Protocol
    info "Checking for raw socket usage (T1095)..."
    
    local raw_sockets
    raw_sockets=$(ss -w 2>/dev/null || true)
    if [ -n "$raw_sockets" ]; then
        warn "Raw sockets detected:"
        echo "$raw_sockets" | tee -a "$HUNT_LOG"
    fi
    
    # Beaconing detection (regular interval connections)
    info "Checking for beaconing patterns..."
    
    # This is a simplified check - real beaconing detection needs more data
    local repeated_conns
    repeated_conns=$(ss -tunapl 2>/dev/null | awk '{print $5}' | sort | uniq -c | sort -rn | head -5 || true)
    if [ -n "$repeated_conns" ]; then
        info "Most frequent connection destinations:"
        echo "$repeated_conns" | tee -a "$HUNT_LOG"
    fi
    
    if [ $found -eq 0 ]; then
        log "No C2 indicators found"
    fi
    
    echo ""
}

#===============================================================================
# EXFILTRATION HUNTING (TA0010)
#===============================================================================

hunt_exfiltration() {
    log "🔍 Hunting for Data Exfiltration (TA0010)..."
    echo ""
    
    local found=0
    
    # T1048 - Exfiltration Over Alternative Protocol
    info "Checking for exfiltration indicators (T1048)..."
    
    # Large outbound transfers
    local large_transfers
    large_transfers=$(find /tmp /var/tmp /home -name "*.tar*" -o -name "*.zip" -o -name "*.7z" -mtime -1 2>/dev/null | head -10 || true)
    if [ -n "$large_transfers" ]; then
        warn "Recent archive files (possible staging):"
        echo "$large_transfers" | tee -a "$HUNT_LOG"
        for f in $large_transfers; do
            ls -lh "$f" >> "$HUNT_LOG" 2>/dev/null || true
        done
    fi
    
    # T1041 - Exfiltration Over C2 Channel
    info "Checking for data staging (T1041)..."
    
    # Files with sensitive data patterns
    local sensitive
    sensitive=$(find /tmp /var/tmp /dev/shm -type f -exec grep -l -E "(password|secret|key|token|credential)" {} \; 2>/dev/null | head -10 || true)
    if [ -n "$sensitive" ]; then
        alert "Files with sensitive keywords in temp directories:"
        echo "$sensitive" | tee -a "$HUNT_LOG"
        found=1
    fi
    
    # T1567 - Exfiltration Over Web Service
    info "Checking for cloud upload indicators (T1567)..."
    
    # Check for cloud CLI tools
    for tool in aws gcloud az rclone; do
        if command -v "$tool" &>/dev/null; then
            info "Cloud tool installed: $tool"
            # Check recent usage
            if [ -f ~/.${tool}/credentials ] || [ -f ~/.config/${tool}/credentials ]; then
                warn "Cloud credentials found for $tool"
            fi
        fi
    done
    
    # Check for curl/wget to cloud services
    local cloud_uploads
    cloud_uploads=$(grep -rE "(s3\.amazonaws|storage\.googleapis|blob\.core\.windows)" /var/log/*.log 2>/dev/null | tail -10 || true)
    if [ -n "$cloud_uploads" ]; then
        warn "Cloud service access in logs:"
        echo "$cloud_uploads" | tee -a "$HUNT_LOG"
    fi
    
    if [ $found -eq 0 ]; then
        log "No exfiltration indicators found"
    fi
    
    echo ""
}

#===============================================================================
# CREDENTIAL ACCESS HUNTING (TA0006)
#===============================================================================

hunt_credential_access() {
    log "🔍 Hunting for Credential Access (TA0006)..."
    echo ""
    
    local found=0
    
    # T1003 - OS Credential Dumping
    info "Checking for credential dumping (T1003)..."
    
    # Check for mimikatz-like tools
    local cred_tools
    cred_tools=$(find / -name "*mimikatz*" -o -name "*lazagne*" -o -name "*secretsdump*" 2>/dev/null | head -5 || true)
    if [ -n "$cred_tools" ]; then
        alert "Credential dumping tools found:"
        echo "$cred_tools" | tee -a "$HUNT_LOG"
        found=1
    fi
    
    # Check for /etc/shadow access
    local shadow_access
    shadow_access=$(grep -E "shadow" /var/log/audit/audit.log 2>/dev/null | tail -10 || true)
    if [ -n "$shadow_access" ]; then
        warn "Shadow file access attempts:"
        echo "$shadow_access" | tee -a "$HUNT_LOG"
    fi
    
    # T1552 - Unsecured Credentials
    info "Checking for unsecured credentials (T1552)..."
    
    # Files with passwords
    local pass_files
    pass_files=$(find /home /root /var/www /opt -type f \( -name "*.conf" -o -name "*.cfg" -o -name "*.ini" -o -name "*.env" \) -exec grep -l -iE "(password|passwd|pwd)\s*=" {} \; 2>/dev/null | head -10 || true)
    if [ -n "$pass_files" ]; then
        warn "Files potentially containing passwords:"
        echo "$pass_files" | tee -a "$HUNT_LOG"
    fi
    
    # SSH private keys
    local ssh_keys
    ssh_keys=$(find /home /root -name "id_rsa" -o -name "id_dsa" -o -name "id_ecdsa" -o -name "id_ed25519" 2>/dev/null || true)
    if [ -n "$ssh_keys" ]; then
        info "SSH private keys found:"
        echo "$ssh_keys" | tee -a "$HUNT_LOG"
        # Check permissions
        for key in $ssh_keys; do
            local perms
            perms=$(stat -c %a "$key" 2>/dev/null || echo "unknown")
            if [ "$perms" != "600" ] && [ "$perms" != "400" ]; then
                warn "Insecure permissions on $key: $perms"
            fi
        done
    fi
    
    # T1110 - Brute Force
    info "Checking for brute force attempts (T1110)..."
    
    local failed_logins
    failed_logins=$(grep -c "Failed password" /var/log/auth.log 2>/dev/null || echo 0)
    if [ "$failed_logins" -gt 100 ]; then
        alert "High number of failed logins: $failed_logins"
        found=1
        
        # Top offending IPs
        local top_ips
        top_ips=$(grep "Failed password" /var/log/auth.log 2>/dev/null | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | sort | uniq -c | sort -rn | head -5 || true)
        if [ -n "$top_ips" ]; then
            alert "Top brute force source IPs:"
            echo "$top_ips" | tee -a "$HUNT_LOG"
        fi
    fi
    
    if [ $found -eq 0 ]; then
        log "No credential access indicators found"
    fi
    
    echo ""
}

#===============================================================================
# FULL HUNT
#===============================================================================

full_hunt() {
    log "Starting comprehensive threat hunt..."
    echo ""
    
    hunt_persistence
    hunt_privilege_escalation
    hunt_defense_evasion
    hunt_lateral_movement
    hunt_c2
    hunt_exfiltration
    hunt_credential_access
    
    echo ""
    log "Threat hunt completed. Results saved to: $HUNT_LOG"
    
    # Summary
    local finding_count
    finding_count=$(find "$FINDINGS_DIR" -name "hunt_*.md" 2>/dev/null | wc -l || echo 0)
    if [ "$finding_count" -gt 0 ]; then
        alert "Generated $finding_count findings in $FINDINGS_DIR"
    fi
}

# Usage
usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --hunt-all          Run all hunting modules"
    echo "  --persistence       Hunt for persistence mechanisms (TA0003)"
    echo "  --privesc           Hunt for privilege escalation (TA0004)"
    echo "  --evasion           Hunt for defense evasion (TA0005)"
    echo "  --lateral           Hunt for lateral movement (TA0008)"
    echo "  --c2                Hunt for C2 communication (TA0011)"
    echo "  --exfil             Hunt for data exfiltration (TA0010)"
    echo "  --creds             Hunt for credential access (TA0006)"
    echo "  -h, --help          Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 --hunt-all"
    echo "  $0 --persistence --privesc"
}

#===============================================================================
# MAIN
#===============================================================================

main() {
    show_banner
    
    mkdir -p "$(dirname "$HUNT_LOG")"
    mkdir -p "$FINDINGS_DIR"
    
    if [ $# -eq 0 ]; then
        full_hunt
        exit 0
    fi
    
    while [ $# -gt 0 ]; do
        case "$1" in
            --hunt-all)
                full_hunt
                ;;
            --persistence)
                hunt_persistence
                ;;
            --privesc)
                hunt_privilege_escalation
                ;;
            --evasion)
                hunt_defense_evasion
                ;;
            --lateral)
                hunt_lateral_movement
                ;;
            --c2)
                hunt_c2
                ;;
            --exfil)
                hunt_exfiltration
                ;;
            --creds)
                hunt_credential_access
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                error "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
        shift
    done
    
    log "Hunt completed. Results: $HUNT_LOG"
}

main "$@"
