#!/usr/bin/env python3
"""
⚪ WHITE TEAM GRC - Report Generator Tool
Genera reportes ejecutivos y técnicos de GRC
"""

import os
import sys
import json
import yaml
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional
from dataclasses import dataclass, field

try:
    import click
    from rich.console import Console
    from rich.table import Table
    from rich.panel import Panel
    from rich.progress import Progress
    from rich import print as rprint
except ImportError:
    print("Installing required packages...")
    os.system("pip install click rich pyyaml")
    import click
    from rich.console import Console
    from rich.table import Table
    from rich.panel import Panel
    from rich.progress import Progress
    from rich import print as rprint

console = Console()

# ══════════════════════════════════════════════════════════════════════════════
# REPORT TEMPLATES
# ══════════════════════════════════════════════════════════════════════════════

EXECUTIVE_TEMPLATE = """# ⚪ WHITE TEAM GRC - Executive Summary

**Report Period:** {period}
**Generated:** {generated_date}
**Classification:** {classification}

---

## 📊 Overall Status

| Metric | Value | Target | Status |
|--------|-------|--------|--------|
| Compliance Score | {compliance_score}% | ≥90% | {compliance_status} |
| Open Risks | {open_risks} | ≤10 | {risk_status} |
| Critical Findings | {critical_findings} | 0 | {findings_status} |
| Controls Implemented | {controls_implemented}% | 100% | {controls_status} |

## 🎯 Key Highlights

{highlights}

## ⚠️ Areas of Concern

{concerns}

## 📈 Trends

### Compliance Trend
{compliance_trend}

### Risk Trend
{risk_trend}

## 🔧 Recommendations

{recommendations}

## 📅 Next Steps

{next_steps}

---

*This report is confidential and intended for executive leadership only.*
"""

KPI_DASHBOARD_TEMPLATE = """# ⚪ WHITE TEAM GRC - KPI Dashboard

**Period:** {period}
**Updated:** {generated_date}

---

## 📊 Key Performance Indicators

### Compliance Metrics

| KPI | Target | Current | Trend | Status |
|-----|--------|---------|-------|--------|
| Overall Compliance | ≥90% | {overall_compliance}% | {compliance_trend} | {compliance_status} |
| ISO 27001 | ≥90% | {iso_compliance}% | {iso_trend} | {iso_status} |
| SOC 2 | ≥90% | {soc_compliance}% | {soc_trend} | {soc_status} |
| PCI-DSS | ≥95% | {pci_compliance}% | {pci_trend} | {pci_status} |

### Risk Metrics

| KPI | Target | Current | Trend | Status |
|-----|--------|---------|-------|--------|
| Critical Risks | 0 | {critical_risks} | {critical_trend} | {critical_status} |
| High Risks | ≤5 | {high_risks} | {high_trend} | {high_status} |
| Risk Score (Avg) | ≤5.0 | {avg_risk_score} | {risk_trend} | {risk_status} |
| Overdue Treatments | 0 | {overdue_treatments} | {overdue_trend} | {overdue_status} |

### Audit Metrics

| KPI | Target | Current | Trend | Status |
|-----|--------|---------|-------|--------|
| Audits Completed | 100% | {audits_completed}% | {audit_trend} | {audit_status} |
| Open Findings | ≤10 | {open_findings} | {findings_trend} | {findings_status} |
| Remediation Rate | ≥95% | {remediation_rate}% | {remediation_trend} | {remediation_status} |
| Avg Remediation Time | ≤30d | {avg_remediation}d | {time_trend} | {time_status} |

### Operational Metrics

| KPI | Target | Current | Trend | Status |
|-----|--------|---------|-------|--------|
| Policy Reviews | 100% | {policy_reviews}% | {policy_trend} | {policy_status} |
| Training Completion | ≥95% | {training_completion}% | {training_trend} | {training_status} |
| Incidents (MTD) | ≤5 | {incidents_mtd} | {incident_trend} | {incident_status} |
| Evidence Currency | ≥90% | {evidence_currency}% | {evidence_trend} | {evidence_status} |

---

## 📈 Trend Charts

### Compliance Over Time
```
100% ┤
 90% ┤     ╭──────╮
 80% ┤ ╭───╯      ╰───╮
 70% ┤─╯              ╰──
 60% ┤
     └─────────────────────
      Jan Feb Mar Apr May
```

### Risk Distribution
```
Critical ██░░░░░░░░ {critical_pct}%
High     ████░░░░░░ {high_pct}%
Medium   ██████░░░░ {medium_pct}%
Low      ████████░░ {low_pct}%
```

---

*Dashboard auto-generated by WHITE TEAM GRC*
"""

# ══════════════════════════════════════════════════════════════════════════════
# REPORT GENERATOR CLASS
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class GRCMetrics:
    compliance_score: float = 0.0
    open_risks: int = 0
    critical_risks: int = 0
    high_risks: int = 0
    medium_risks: int = 0
    low_risks: int = 0
    open_findings: int = 0
    critical_findings: int = 0
    controls_implemented: float = 0.0
    audits_completed: float = 0.0
    remediation_rate: float = 0.0
    avg_remediation_days: int = 0
    policy_reviews: float = 0.0
    training_completion: float = 0.0
    incidents_mtd: int = 0
    evidence_currency: float = 0.0
    iso_compliance: float = 0.0
    soc_compliance: float = 0.0
    pci_compliance: float = 0.0

class ReportGenerator:
    def __init__(self, workspace_path: str = "."):
        self.workspace = Path(workspace_path)
        self.reports_path = self.workspace / "reports"
        self.risks_path = self.workspace / "risks" / "register"
        self.audits_path = self.workspace / "audits"
        self.controls_path = self.workspace / "controls"
        
    def collect_metrics(self) -> GRCMetrics:
        """Collect metrics from workspace data"""
        metrics = GRCMetrics()
        
        # Load risks
        if self.risks_path.exists():
            risks = list(self.risks_path.glob("*.yaml"))
            metrics.open_risks = len(risks)
            
            for risk_file in risks:
                try:
                    with open(risk_file, 'r') as f:
                        risk = yaml.safe_load(f)
                        if risk:
                            level = risk.get('residual_risk', {}).get('level', 'medium')
                            if level == 'critical':
                                metrics.critical_risks += 1
                            elif level == 'high':
                                metrics.high_risks += 1
                            elif level == 'medium':
                                metrics.medium_risks += 1
                            else:
                                metrics.low_risks += 1
                except:
                    pass
        
        # Load audit findings
        findings_path = self.audits_path / "findings"
        if findings_path.exists():
            findings = list(findings_path.glob("*.yaml"))
            metrics.open_findings = len(findings)
            
            for finding_file in findings:
                try:
                    with open(finding_file, 'r') as f:
                        finding = yaml.safe_load(f)
                        if finding and finding.get('severity') == 'critical':
                            metrics.critical_findings += 1
                except:
                    pass
        
        # Set default values for demo
        if metrics.open_risks == 0:
            metrics.compliance_score = 87.5
            metrics.open_risks = 12
            metrics.critical_risks = 2
            metrics.high_risks = 4
            metrics.medium_risks = 4
            metrics.low_risks = 2
            metrics.open_findings = 8
            metrics.critical_findings = 1
            metrics.controls_implemented = 94.0
            metrics.audits_completed = 80.0
            metrics.remediation_rate = 92.0
            metrics.avg_remediation_days = 25
            metrics.policy_reviews = 100.0
            metrics.training_completion = 92.0
            metrics.incidents_mtd = 3
            metrics.evidence_currency = 88.0
            metrics.iso_compliance = 85.0
            metrics.soc_compliance = 92.0
            metrics.pci_compliance = 88.0
        
        return metrics
    
    def get_status_emoji(self, value: float, target: float, higher_is_better: bool = True) -> str:
        """Get status emoji based on value vs target"""
        if higher_is_better:
            if value >= target:
                return "🟢"
            elif value >= target * 0.8:
                return "🟡"
            else:
                return "🔴"
        else:
            if value <= target:
                return "🟢"
            elif value <= target * 1.2:
                return "🟡"
            else:
                return "🔴"
    
    def get_trend_emoji(self, improving: bool = True) -> str:
        """Get trend emoji"""
        return "📈" if improving else "📉"
    
    def generate_executive_report(self, period: str = "Monthly") -> str:
        """Generate executive summary report"""
        metrics = self.collect_metrics()
        
        highlights = """
- Compliance score improved by 5% compared to last period
- Successfully completed SOC 2 Type II audit
- Zero critical security incidents this period
- All mandatory policies reviewed and updated
"""
        
        concerns = """
- 2 critical risks require immediate attention
- PCI-DSS compliance below target (88% vs 95%)
- 3 overdue remediation items
- Training completion slightly below target
"""
        
        recommendations = """
1. **Prioritize Critical Risks**: Address the 2 critical risks within 7 days
2. **PCI-DSS Remediation**: Focus on requirements 8 and 10 to improve compliance
3. **Training Push**: Send reminders to complete mandatory security training
4. **Evidence Collection**: Update evidence for Q2 audit preparation
"""
        
        next_steps = """
- [ ] Critical risk remediation meeting (Week 1)
- [ ] PCI-DSS gap remediation kickoff (Week 1)
- [ ] Training completion follow-up (Week 2)
- [ ] Q2 audit preparation review (Week 3)
- [ ] Board security update presentation (Week 4)
"""
        
        report = EXECUTIVE_TEMPLATE.format(
            period=period,
            generated_date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            classification="CONFIDENTIAL",
            compliance_score=metrics.compliance_score,
            compliance_status=self.get_status_emoji(metrics.compliance_score, 90),
            open_risks=metrics.open_risks,
            risk_status=self.get_status_emoji(metrics.open_risks, 10, False),
            critical_findings=metrics.critical_findings,
            findings_status=self.get_status_emoji(metrics.critical_findings, 0, False),
            controls_implemented=metrics.controls_implemented,
            controls_status=self.get_status_emoji(metrics.controls_implemented, 100),
            highlights=highlights,
            concerns=concerns,
            compliance_trend="Improving (+5% MoM)",
            risk_trend="Stable (no new critical risks)",
            recommendations=recommendations,
            next_steps=next_steps
        )
        
        return report
    
    def generate_kpi_dashboard(self, period: str = "Monthly") -> str:
        """Generate KPI dashboard"""
        metrics = self.collect_metrics()
        
        total_risks = metrics.critical_risks + metrics.high_risks + metrics.medium_risks + metrics.low_risks
        if total_risks > 0:
            critical_pct = int((metrics.critical_risks / total_risks) * 100)
            high_pct = int((metrics.high_risks / total_risks) * 100)
            medium_pct = int((metrics.medium_risks / total_risks) * 100)
            low_pct = int((metrics.low_risks / total_risks) * 100)
        else:
            critical_pct = high_pct = medium_pct = low_pct = 0
        
        avg_risk_score = 5.2  # Demo value
        
        report = KPI_DASHBOARD_TEMPLATE.format(
            period=period,
            generated_date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            overall_compliance=metrics.compliance_score,
            compliance_trend="📈",
            compliance_status=self.get_status_emoji(metrics.compliance_score, 90),
            iso_compliance=metrics.iso_compliance,
            iso_trend="📈",
            iso_status=self.get_status_emoji(metrics.iso_compliance, 90),
            soc_compliance=metrics.soc_compliance,
            soc_trend="📈",
            soc_status=self.get_status_emoji(metrics.soc_compliance, 90),
            pci_compliance=metrics.pci_compliance,
            pci_trend="📉",
            pci_status=self.get_status_emoji(metrics.pci_compliance, 95),
            critical_risks=metrics.critical_risks,
            critical_trend="➡️",
            critical_status=self.get_status_emoji(metrics.critical_risks, 0, False),
            high_risks=metrics.high_risks,
            high_trend="📉",
            high_status=self.get_status_emoji(metrics.high_risks, 5, False),
            avg_risk_score=avg_risk_score,
            risk_trend="📈",
            risk_status=self.get_status_emoji(5.0, avg_risk_score),
            overdue_treatments=3,
            overdue_trend="📉",
            overdue_status="🟡",
            audits_completed=metrics.audits_completed,
            audit_trend="📈",
            audit_status=self.get_status_emoji(metrics.audits_completed, 100),
            open_findings=metrics.open_findings,
            findings_trend="📉",
            findings_status=self.get_status_emoji(metrics.open_findings, 10, False),
            remediation_rate=metrics.remediation_rate,
            remediation_trend="📈",
            remediation_status=self.get_status_emoji(metrics.remediation_rate, 95),
            avg_remediation=metrics.avg_remediation_days,
            time_trend="📈",
            time_status=self.get_status_emoji(30, metrics.avg_remediation_days),
            policy_reviews=metrics.policy_reviews,
            policy_trend="➡️",
            policy_status=self.get_status_emoji(metrics.policy_reviews, 100),
            training_completion=metrics.training_completion,
            training_trend="📈",
            training_status=self.get_status_emoji(metrics.training_completion, 95),
            incidents_mtd=metrics.incidents_mtd,
            incident_trend="📉",
            incident_status=self.get_status_emoji(metrics.incidents_mtd, 5, False),
            evidence_currency=metrics.evidence_currency,
            evidence_trend="📈",
            evidence_status=self.get_status_emoji(metrics.evidence_currency, 90),
            critical_pct=critical_pct,
            high_pct=high_pct,
            medium_pct=medium_pct,
            low_pct=low_pct
        )
        
        return report
    
    def generate_compliance_report(self) -> str:
        """Generate detailed compliance report"""
        metrics = self.collect_metrics()
        
        report = f"""# ⚪ WHITE TEAM GRC - Compliance Status Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Period:** {datetime.now().strftime("%B %Y")}

---

## 📊 Compliance Summary

| Framework | Score | Status | Trend |
|-----------|-------|--------|-------|
| ISO 27001:2022 | {metrics.iso_compliance}% | {self.get_status_emoji(metrics.iso_compliance, 90)} | 📈 |
| SOC 2 Type II | {metrics.soc_compliance}% | {self.get_status_emoji(metrics.soc_compliance, 90)} | 📈 |
| PCI-DSS v4.0 | {metrics.pci_compliance}% | {self.get_status_emoji(metrics.pci_compliance, 95)} | 📉 |
| GDPR | 95% | 🟢 | ➡️ |
| HIPAA | 88% | 🟡 | 📈 |
| NIST CSF | 82% | 🟡 | 📈 |

## 🔍 Gap Summary

### Critical Gaps (Immediate Action Required)

| Framework | Control | Gap | Owner | Due Date |
|-----------|---------|-----|-------|----------|
| PCI-DSS | 8.4 | MFA not enforced for all CDE access | IT Security | 2024-02-15 |
| ISO 27001 | A.8.2 | PAM solution not fully deployed | IT Ops | 2024-02-28 |

### High Priority Gaps

| Framework | Control | Gap | Owner | Due Date |
|-----------|---------|-----|-------|----------|
| SOC 2 | CC7.1 | SIEM coverage incomplete | Security | 2024-03-15 |
| HIPAA | 164.312(b) | Audit log retention < 6 years | IT Ops | 2024-03-30 |
| NIST CSF | DE.CM-1 | Network monitoring gaps | Network | 2024-03-30 |

## 📈 Remediation Progress

| Priority | Total | Completed | In Progress | Overdue |
|----------|-------|-----------|-------------|---------|
| Critical | 5 | 3 | 2 | 0 |
| High | 12 | 8 | 3 | 1 |
| Medium | 25 | 18 | 5 | 2 |
| Low | 15 | 12 | 3 | 0 |

## 📅 Upcoming Deadlines

- **Feb 15**: PCI-DSS MFA implementation
- **Feb 28**: PAM deployment completion
- **Mar 15**: SIEM coverage expansion
- **Mar 30**: Audit log retention fix
- **Apr 15**: Q2 compliance review

---

*Report generated by WHITE TEAM GRC Compliance Check Tool*
"""
        return report
    
    def save_report(self, report: str, report_type: str) -> str:
        """Save report to file"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        report_dir = self.reports_path / report_type
        report_dir.mkdir(parents=True, exist_ok=True)
        
        filename = f"{report_type}_report_{timestamp}.md"
        filepath = report_dir / filename
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(report)
        
        return str(filepath)
    
    def display_report(self, report: str) -> None:
        """Display report in console"""
        console.print(Panel.fit(
            "[bold white]⚪ WHITE TEAM GRC - Report Generated[/bold white]",
            border_style="white"
        ))
        console.print(report)

# ══════════════════════════════════════════════════════════════════════════════
# CLI INTERFACE
# ══════════════════════════════════════════════════════════════════════════════

@click.command()
@click.option('--type', '-t', 'report_type', 
              type=click.Choice(['executive', 'kpi', 'compliance', 'full']),
              default='executive', help='Report type to generate')
@click.option('--period', '-p', type=str, default='Monthly', help='Report period')
@click.option('--format', '-f', type=click.Choice(['console', 'markdown', 'both']),
              default='both', help='Output format')
@click.option('--workspace', '-w', type=click.Path(exists=True), default='.', help='Workspace path')
@click.version_option(version='1.0.0', prog_name='WHITE TEAM GRC - Report Generator')
def main(report_type: str, period: str, format: str, workspace: str):
    """
    ⚪ WHITE TEAM GRC - Report Generator Tool
    
    Genera reportes ejecutivos y técnicos de GRC.
    """
    generator = ReportGenerator(workspace)
    
    reports = []
    
    if report_type in ['executive', 'full']:
        report = generator.generate_executive_report(period)
        reports.append(('executive', report))
    
    if report_type in ['kpi', 'full']:
        report = generator.generate_kpi_dashboard(period)
        reports.append(('kpi', report))
    
    if report_type in ['compliance', 'full']:
        report = generator.generate_compliance_report()
        reports.append(('compliance', report))
    
    for rtype, report in reports:
        if format in ['console', 'both']:
            generator.display_report(report)
        
        if format in ['markdown', 'both']:
            filepath = generator.save_report(report, rtype)
            console.print(f"\n[green]✓ Report saved to: {filepath}[/green]")

if __name__ == '__main__':
    main()
